name: minga_shared
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  bloc: ^6.0.1
  firestore_api:
    git:
      url: https://github.com/dartclub/firestore_dart
      path: firestore_api
  firestore_annotations: ^0.0.2
  equatable: ^1.0.0
  mapbox_search:
    git:
      url:  https://github.com/dartclub/mapbox_search
      ref: turf-based
  cloudinary_client:
    git: https://github.com/dartclub/cloudinary_client
  turf: 0.0.1+5
dev_dependencies:
  dartclub_lint: 0.2.1
  test: ^1.6.0
  bloc_test: ^7.0.0
  build_runner: ^1.5.0
  firestore_serializable: ^0.0.17+2

builders:
  firestore_serializable: any
