name: minga_flutter_test
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  dartclub_lint: 0.2.1
  test: ^1.6.0
  bloc_test: ^7.0.0
  build_runner: ^1.5.0
  firestore_serializable: ^0.0.17+2
  firebase_auth_mocks: ^0.2.1
  cloud_firestore_mocks: ^0.4.6+1
  firestore_api:
    git:
      url: https://github.com/dartclub/firestore_dart
      path: firestore_api
  firestore_flutter:
    git:
      url: https://github.com/dartclub/firestore_dart
      path: firestore_flutter
  minga_shared:
    path: ..
  flutter_test:
    sdk: flutter